name: "Nose to PyTest"
on: [push, workflow_dispatch]

jobs:
  nose2pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - run: pip install -U wheel pip setuptools
    - run: pip install -e git+https://github.com/pytest-dev/nose2pytest#egg=nose2pytest
    - run: nose2pytest EMAworkbench
    - uses: peter-evans/create-pull-request@v4
      with:
        title: "Nose to PyTest"
        branch: nose2pytest
        commit-message: "Migrate test from Nose to PyTest"
